"""Shared pytest configuration for ChristCalm integration tests."""

import os
from pathlib import Path

import pytest
from dotenv import load_dotenv

ROOT = Path(__file__).resolve().parents[1]

# Public API URL only (generated by ./scripts/sync-env-from-aws.sh). No secrets.
load_dotenv(ROOT / "frontend" / ".env")
# Optional non-secret backend flags (SSM_PREFIX, region) — secrets come from SSM at runtime.
load_dotenv(ROOT / "backend" / ".env")

BASE_URL = os.environ.get("EXPO_PUBLIC_BACKEND_URL", "").rstrip("/")


@pytest.fixture(scope="session")
def base_url() -> str:
    if not BASE_URL:
        pytest.skip("Run ./scripts/sync-env-from-aws.sh (needs EXPO_PUBLIC_BACKEND_URL)")
    return BASE_URL