#!/usr/bin/env bash
# One-shot deploy for a *new* AWS account (or clean workspace).
#
# Assumes:
#   - AWS credentials for the target account (IAM admin recommended — not root)
#   - Bedrock model access enabled in the region
#   - terraform, aws, node/npm, python3, openssl installed
#
# What it does:
#   1. Detects account id + region
#   2. Writes infrastructure/terraform/terraform.tfvars with that account id
#      (JWT secret auto-generated; resources named christcalm-preview-<account_id>)
#   3. terraform apply → creates stack + populates SSM
#   4. Deploys Lambda code via CodeBuild
#   5. Syncs disposable frontend/backend .env (no secrets)
#   6. Seeds Cognito test user
#
# Usage:
#   ./scripts/bootstrap-new-account.sh
#   ./scripts/bootstrap-new-account.sh --region us-west-2
#   ./scripts/bootstrap-new-account.sh --force   # overwrite existing tfvars
#
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
source "$ROOT/scripts/lib/aws-auth.sh"

FORCE=0
REGION_OVERRIDE=""
while [[ $# -gt 0 ]]; do
  case "$1" in
    --force) FORCE=1; shift ;;
    --region) REGION_OVERRIDE="${2:-}"; shift 2 ;;
    -h|--help)
      sed -n '2,30p' "$0" | sed 's/^# \{0,1\}//'
      exit 0
      ;;
    *)
      echo "Unknown arg: $1" >&2
      exit 1
      ;;
  esac
done

aws_auth_require
export AWS_REGION="${REGION_OVERRIDE:-$(aws_auth_region)}"
export AWS_DEFAULT_REGION="$AWS_REGION"
export TF_VAR_aws_region="$AWS_REGION"

ACCOUNT_ID="$(aws sts get-caller-identity --query Account --output text)"
ARN="$(aws sts get-caller-identity --query Arn --output text)"
TF_DIR="$ROOT/infrastructure/terraform"
TFVARS="$TF_DIR/terraform.tfvars"

echo ""
echo "ChristCalm — bootstrap new AWS account"
echo "  Account:  $ACCOUNT_ID"
echo "  Identity: $ARN"
echo "  Region:   $AWS_REGION"
echo "  Names:    christcalm-preview-${ACCOUNT_ID}-*"
echo "  SSM:      /christcalm-preview-${ACCOUNT_ID}/*"
echo ""

# Safety: never clobber an existing tfvars without --force
if [[ -f "$TFVARS" && "$FORCE" -ne 1 ]]; then
  echo "Found existing $TFVARS"
  echo "  Re-run with --force to regenerate, or use:"
  echo "    ./scripts/deploy-aws.sh deploy"
  echo "    ./scripts/sync-env-from-aws.sh"
  exit 1
fi

# Generate secrets / non-secret defaults (no Apple/RevenueCat required for core)
JWT_SECRET="$(openssl rand -base64 48 | tr -d '\n=/+' | head -c 48)"
if [[ ${#JWT_SECRET} -lt 32 ]]; then
  JWT_SECRET="$(python3 -c 'import secrets; print(secrets.token_urlsafe(36))')"
fi

NAME_PREFIX="christcalm-preview-${ACCOUNT_ID}"

cat > "$TFVARS" <<EOF
# AUTO-GENERATED by scripts/bootstrap-new-account.sh — do not commit
# Account: ${ACCOUNT_ID}  Region: ${AWS_REGION}
# Safe to delete and re-bootstrap with --force (will recreate resources if names change)

aws_region  = "${AWS_REGION}"
environment = "preview"
project_name = "christcalm"

# Isolates this stack from other AWS accounts / shared Cognito domains
name_suffix = "${ACCOUNT_ID}"

# Matches name_prefix (christcalm-preview-<account_id>)
dynamodb_table_prefix = "${NAME_PREFIX}"

jwt_secret = "${JWT_SECRET}"

# Preview: skip email verification for easy testing
cognito_auto_confirm_users = true

# Optional social — leave empty until you have Apple Developer credentials
# apple_services_id  = ""
# apple_team_id      = ""
# apple_key_id       = ""
# apple_private_key  = ""

# SSM SecureString requires non-empty values
google_client_id     = "unset"
google_client_secret = "unset"
google_redirect_uri  = "unset"

cors_origins = [
  "exp://127.0.0.1:8081",
  "exp://localhost:8081",
  "http://localhost:8081",
  "http://127.0.0.1:8081",
]

llm_provider     = "bedrock"
bedrock_model_id = "openai.gpt-oss-20b-1:0"
openai_api_key   = ""
openai_model     = "gpt-4o"

revenuecat_webhook_authorization = ""
revenuecat_entitlement_id        = "christcalm_premium"
EOF

echo "Wrote $TFVARS (gitignored)"
echo ""

# Full deploy: infra + Lambda package
echo ">>> Deploying infrastructure + Lambda code…"
"$ROOT/scripts/deploy-aws.sh" deploy

echo ""
echo ">>> Syncing disposable local env (public config only)…"
"$ROOT/scripts/sync-env-from-aws.sh"

echo ""
echo ">>> Seeding Cognito test user…"
TEST_EMAIL="test@christcalm.dev"
TEST_PASS="Test1234"
if "$ROOT/scripts/seed-test-user.sh" "$TEST_EMAIL" "$TEST_PASS" "Test User"; then
  :
else
  echo "  (seed-test-user failed — Cognito may still be settling; re-run: ./scripts/seed-test-user.sh)"
fi

API_URL="$(cd "$TF_DIR" && terraform output -raw api_url 2>/dev/null || true)"
POOL="$(cd "$TF_DIR" && terraform output -raw cognito_user_pool_id 2>/dev/null || true)"
SSM="$(cd "$TF_DIR" && terraform output -raw ssm_prefix 2>/dev/null || true)"

echo ""
echo "=============================================="
echo " Bootstrap complete for account ${ACCOUNT_ID}"
echo "=============================================="
echo "  API:        ${API_URL}"
echo "  Cognito:    ${POOL}"
echo "  SSM prefix: ${SSM}"
echo "  Test login: ${TEST_EMAIL} / ${TEST_PASS}"
echo ""
echo "  Preview UI: ./scripts/preview.sh"
echo "  Local API:  ./scripts/run-backend-local.sh"
echo ""
echo "  Note: Apple Sign-In / RevenueCat need extra credentials later."
echo "  Bedrock: ensure model access is enabled in ${AWS_REGION}."
echo "=============================================="
