#!/usr/bin/env bash
# Regenerate disposable local env files from AWS (Terraform outputs + public config only).
# Secrets stay in SSM — never written here.
#
#   ./scripts/sync-env-from-aws.sh
#
# Safe to delete frontend/.env and backend/.env anytime; re-run this script.
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
TF_DIR="$ROOT/infrastructure/terraform"
source "$ROOT/scripts/lib/aws-auth.sh"
aws_auth_require

export AWS_REGION="$(aws_auth_region)"
cd "$TF_DIR"
terraform init -input=false >/dev/null

API_URL="$(terraform output -raw api_url)"
POOL_ID="$(terraform output -raw cognito_user_pool_id)"
CLIENT_ID="$(terraform output -raw cognito_client_id)"
COGNITO_DOMAIN="$(terraform output -raw cognito_domain)"
COGNITO_REGION="$(terraform output -raw cognito_region)"
SSM_PREFIX="$(terraform output -raw ssm_prefix 2>/dev/null || echo "/christcalm-preview")"
TABLE_PREFIX="$(terraform output -json dynamodb_tables 2>/dev/null | python3 -c 'import sys,json; d=json.load(sys.stdin); print(d.get("users","").rsplit("-users",1)[0] if d else "christcalm-preview")' 2>/dev/null || echo "christcalm-preview")"

# --- Frontend: public Expo vars only (shipped in the client bundle) ---
cat > "$ROOT/frontend/.env" <<EOF
# AUTO-GENERATED by scripts/sync-env-from-aws.sh — safe to delete and re-run.
# No secrets. Source of truth: Terraform outputs + SSM (for the API).
EXPO_PUBLIC_BACKEND_URL=${API_URL%/}
EXPO_PUBLIC_COGNITO_USER_POOL_ID=${POOL_ID}
EXPO_PUBLIC_COGNITO_CLIENT_ID=${CLIENT_ID}
EXPO_PUBLIC_COGNITO_DOMAIN=${COGNITO_DOMAIN}
EXPO_PUBLIC_COGNITO_REGION=${COGNITO_REGION}
EOF

# --- Backend: non-secret local flags only; secrets load from SSM at runtime ---
cat > "$ROOT/backend/.env" <<EOF
# AUTO-GENERATED by scripts/sync-env-from-aws.sh — safe to delete and re-run.
# Secrets are NOT stored here. Runtime loads them from SSM_PREFIX via AWS credentials.
AWS_REGION=${AWS_REGION}
SSM_PREFIX=${SSM_PREFIX}
DYNAMODB_TABLE_PREFIX=${TABLE_PREFIX}
EOF

echo "Wrote disposable local env (no secrets):"
echo "  frontend/.env  (public Expo config)"
echo "  backend/.env   (SSM_PREFIX + region + table prefix only)"
echo ""
echo "  SSM secrets path: ${SSM_PREFIX}/*"
echo "  API:              ${API_URL%/}"
echo ""
echo "Local API:  ./scripts/run-backend-local.sh"
echo "Preview UI: ./scripts/preview.sh"
