#!/usr/bin/env bash
# Pull public frontend config from GitHub Actions repository VARIABLES into frontend/.env
#
# Use this when you do NOT have AWS credentials (typical for UI contributors).
# Infra and secrets stay on the owner's AWS account (SSM). Only public EXPO_PUBLIC_*
# values are stored as GitHub Variables (readable by collaborators with repo access).
#
# Prerequisites:
#   - gh CLI authenticated (gh auth login)
#   - Read access to the ChristCalm GitHub repo
#
# Owner: after rotating API/Cognito, re-push with:
#   ./scripts/push-env-to-github.sh
#
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
REPO="${GITHUB_REPO:-shivanshu-gupta-ai/SleepMeditationApp-ChristCalm}"
OUT="${FRONTEND_ENV:-$ROOT/frontend/.env}"

if ! command -v gh >/dev/null 2>&1; then
  echo "Install GitHub CLI: https://cli.github.com/" >&2
  exit 1
fi

if ! gh auth status >/dev/null 2>&1; then
  echo "Not logged in. Run: gh auth login" >&2
  exit 1
fi

VARS=(
  EXPO_PUBLIC_BACKEND_URL
  EXPO_PUBLIC_COGNITO_USER_POOL_ID
  EXPO_PUBLIC_COGNITO_CLIENT_ID
  EXPO_PUBLIC_COGNITO_DOMAIN
  EXPO_PUBLIC_COGNITO_REGION
  EXPO_PUBLIC_REVENUECAT_IOS_API_KEY
  EXPO_PUBLIC_REVENUECAT_ENTITLEMENT_ID
  EXPO_PUBLIC_REVENUECAT_OFFERING_ID
  EXPO_PUBLIC_REVENUECAT_PRODUCT_MONTHLY
  EXPO_PUBLIC_REVENUECAT_PRODUCT_ANNUAL
  EXPO_PUBLIC_UNLOCK_ALL
)

echo "Syncing public env from GitHub Variables → $OUT"
echo "  Repo: $REPO"
mkdir -p "$(dirname "$OUT")"

{
  echo "# Generated by scripts/sync-env-from-github.sh — do not commit"
  echo "# Public EXPO_PUBLIC_* only. Infra stays on owner AWS (SSM)."
  echo "# Source: GitHub Actions Variables on $REPO"
  echo ""
} >"$OUT"

missing=0
for name in "${VARS[@]}"; do
  if value=$(gh variable get "$name" -R "$REPO" 2>/dev/null); then
    # Escape nothing special for dotenv simple values
    printf '%s=%s\n' "$name" "$value" >>"$OUT"
    echo "  ✓ $name"
  else
    echo "  ✗ $name (not set on repo — ask the owner to run ./scripts/push-env-to-github.sh)"
    missing=1
  fi
done

echo ""
if [[ "$missing" -eq 1 ]]; then
  echo "Some variables missing. You can still fill gaps from config/env/frontend.env.example"
  exit 1
fi

echo "Done. Next:"
echo "  cd frontend && npm install && npx expo start"
echo "  Test login: test@christcalm.dev / Test1234"
echo ""
echo "Do NOT commit frontend/.env"
