#!/usr/bin/env bash
# Regenerate disposable local env files from AWS (Terraform outputs + public config only).
# Secrets stay in SSM — never written here.
#
#   ./scripts/sync-env-from-aws.sh
#
# Safe to delete frontend/.env and backend/.env anytime; re-run this script.
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
TF_DIR="$ROOT/infrastructure/terraform"
source "$ROOT/scripts/lib/aws-auth.sh"
aws_auth_require

export AWS_REGION="$(aws_auth_region)"
cd "$TF_DIR"
terraform init -input=false >/dev/null

API_URL="$(terraform output -raw api_url)"
POOL_ID="$(terraform output -raw cognito_user_pool_id)"
CLIENT_ID="$(terraform output -raw cognito_client_id)"
COGNITO_DOMAIN="$(terraform output -raw cognito_domain)"
COGNITO_REGION="$(terraform output -raw cognito_region)"
SSM_PREFIX="$(terraform output -raw ssm_prefix 2>/dev/null || echo "/christcalm-dev")"
TABLE_PREFIX="$(terraform output -json dynamodb_tables 2>/dev/null | python3 -c 'import sys,json; d=json.load(sys.stdin); print(d.get("users","").rsplit("-users",1)[0] if d else "christcalm-dev")' 2>/dev/null || echo "christcalm-dev")"

# Preserve existing public RevenueCat keys if present (not in Terraform)
RC_IOS_KEY=""
RC_ENT=""
RC_OFF=""
RC_MONTHLY=""
RC_ANNUAL=""
if [[ -f "$ROOT/frontend/.env" ]]; then
  RC_IOS_KEY="$(grep -E '^EXPO_PUBLIC_REVENUECAT_IOS_API_KEY=' "$ROOT/frontend/.env" | cut -d= -f2- || true)"
  RC_ENT="$(grep -E '^EXPO_PUBLIC_REVENUECAT_ENTITLEMENT_ID=' "$ROOT/frontend/.env" | cut -d= -f2- || true)"
  RC_OFF="$(grep -E '^EXPO_PUBLIC_REVENUECAT_OFFERING_ID=' "$ROOT/frontend/.env" | cut -d= -f2- || true)"
  RC_MONTHLY="$(grep -E '^EXPO_PUBLIC_REVENUECAT_PRODUCT_MONTHLY=' "$ROOT/frontend/.env" | cut -d= -f2- || true)"
  RC_ANNUAL="$(grep -E '^EXPO_PUBLIC_REVENUECAT_PRODUCT_ANNUAL=' "$ROOT/frontend/.env" | cut -d= -f2- || true)"
fi
# Defaults: Test Store key for local; product ids match ASC + RC (aliases supported in app)
RC_IOS_KEY="${RC_IOS_KEY:-test_iOFZidqNcAXQabRbTcHHYiAEKug}"
RC_ENT="${RC_ENT:-christcalm_premium}"
RC_OFF="${RC_OFF:-default}"
RC_MONTHLY="${RC_MONTHLY:-cc_999_1m}"
RC_ANNUAL="${RC_ANNUAL:-cc_1999_1y_1w0}"

# --- Frontend: public Expo vars only (shipped in the client bundle) ---
cat > "$ROOT/frontend/.env" <<EOF
# AUTO-GENERATED by scripts/sync-env-from-aws.sh — safe to delete and re-run.
# No secrets. Source of truth: Terraform outputs + SSM (for the API).
EXPO_PUBLIC_BACKEND_URL=${API_URL%/}
EXPO_PUBLIC_COGNITO_USER_POOL_ID=${POOL_ID}
EXPO_PUBLIC_COGNITO_CLIENT_ID=${CLIENT_ID}
EXPO_PUBLIC_COGNITO_DOMAIN=${COGNITO_DOMAIN}
EXPO_PUBLIC_COGNITO_REGION=${COGNITO_REGION}

# RevenueCat — iOS only (public SDK key; Test Store for sandbox)
EXPO_PUBLIC_REVENUECAT_IOS_API_KEY=${RC_IOS_KEY}
EXPO_PUBLIC_REVENUECAT_ENTITLEMENT_ID=${RC_ENT}
EXPO_PUBLIC_REVENUECAT_OFFERING_ID=${RC_OFF}
EXPO_PUBLIC_REVENUECAT_PRODUCT_MONTHLY=${RC_MONTHLY}
EXPO_PUBLIC_REVENUECAT_PRODUCT_ANNUAL=${RC_ANNUAL}
EOF

# --- Backend: non-secret local flags only; secrets load from SSM at runtime ---
cat > "$ROOT/backend/.env" <<EOF
# AUTO-GENERATED by scripts/sync-env-from-aws.sh — safe to delete and re-run.
# Secrets are NOT stored here. Runtime loads them from SSM_PREFIX via AWS credentials.
AWS_REGION=${AWS_REGION}
SSM_PREFIX=${SSM_PREFIX}
DYNAMODB_TABLE_PREFIX=${TABLE_PREFIX}
EOF

echo "Wrote disposable local env (no secrets):"
echo "  frontend/.env  (public Expo config)"
echo "  backend/.env   (SSM_PREFIX + region + table prefix only)"
echo ""
echo "  SSM secrets path: ${SSM_PREFIX}/*"
echo "  API:              ${API_URL%/}"
echo ""
echo "Local API:  ./scripts/run-backend-local.sh"
echo "Preview UI: ./scripts/preview.sh"
